{"name": "test_add2[7-8-15]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 22 == 8\n +  where 22 = add(7, 15)", "trace": "self = <test_case.test_3.TestAbc object at 0x0545B4A8>, a = 7, b = 8, c = 15\n\n    def test_add2(self,a,b,c):  # => 作为用例参数，接收装饰器传入的数据\n>       assert add(a, c) == b\nE       assert 22 == 8\nE        +  where 22 = add(7, 15)\n\ntest_case\\test_3.py:11: AssertionError"}, "parameters": [{"name": "a", "value": "7"}, {"name": "b", "value": "8"}, {"name": "c", "value": "15"}], "start": 1605850093611, "stop": 1605850093611, "uuid": "b57741e7-7261-4b1a-8c6d-6c0c9b74068b", "historyId": "bb4ece5a4d4c1539732124e1f956e730", "testCaseId": "48dace7bcfa93fab0e591da0a625ef44", "fullName": "test_case.test_3.TestAbc#test_add2", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_3"}, {"name": "subSuite", "value": "TestAbc"}, {"name": "host", "value": "DESKTOP-EQA5M9D"}, {"name": "thread", "value": "22012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_3"}]}